[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p uploads logs"]

[start]
cmd = "python main.py api"
